# Generated by Django 5.2.17 on 2026-09-28 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0007_pricelist_itemprice_pricelistcountry'),
        ('geo', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerGroup',
            fields=[
                ('name', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('is_group', models.BooleanField(default=False)),
                ('lft', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('rgt', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('default_price_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_groups', to='catalog.pricelist')),
                ('parent_customer_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='parties.customergroup')),
            ],
            options={
                'db_table': 'customer_group',
                'ordering': ('lft', 'name'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupplierGroup',
            fields=[
                ('name', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('is_group', models.BooleanField(default=False)),
                ('lft', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('rgt', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('parent_supplier_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='parties.suppliergroup')),
            ],
            options={
                'db_table': 'supplier_group',
                'ordering': ('lft', 'name'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('name', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=140)),
                ('supplier_type', models.CharField(choices=[('Company', 'Company'), ('Individual', 'Individual'), ('Partnership', 'Partnership')], default='Company', max_length=20)),
                ('disabled', models.BooleanField(default=False)),
                ('is_internal_supplier', models.BooleanField(default=False)),
                ('tax_id', models.CharField(blank=True, max_length=140)),
                ('website', models.CharField(blank=True, max_length=140)),
                ('supplier_details', models.TextField(blank=True)),
                ('on_hold', models.BooleanField(default=False)),
                ('hold_type', models.CharField(choices=[('All', 'All'), ('Invoices', 'Invoices'), ('Payments', 'Payments')], default='All', max_length=10)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='suppliers', to='geo.country')),
                ('default_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='suppliers', to='geo.currency')),
                ('default_price_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='suppliers', to='catalog.pricelist')),
                ('represents_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='internal_suppliers', to='organizations.company')),
                ('supplier_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='suppliers', to='parties.suppliergroup')),
            ],
            options={
                'db_table': 'supplier',
            },
        ),
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('name', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('is_group', models.BooleanField(default=False)),
                ('lft', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('rgt', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('parent_territory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='parties.territory')),
            ],
            options={
                'db_table': 'territory',
                'ordering': ('lft', 'name'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('name', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=140)),
                ('customer_type', models.CharField(choices=[('Company', 'Company'), ('Individual', 'Individual'), ('Partnership', 'Partnership')], default='Company', max_length=20)),
                ('disabled', models.BooleanField(default=False)),
                ('is_internal_customer', models.BooleanField(default=False)),
                ('tax_id', models.CharField(blank=True, max_length=140)),
                ('website', models.CharField(blank=True, max_length=140)),
                ('customer_details', models.TextField(blank=True)),
                ('on_hold', models.BooleanField(default=False)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('default_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='geo.currency')),
                ('default_price_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='catalog.pricelist')),
                ('represents_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='internal_customers', to='organizations.company')),
                ('customer_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='parties.customergroup')),
                ('territory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='parties.territory')),
            ],
            options={
                'db_table': 'customer',
            },
        ),
    ]
