# Generated by Django 5.2.17 on 2026-09-28 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_primary_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='primary_for_customers', to='contacts.address'),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_primary_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='primary_for_customers', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier_primary_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='primary_for_suppliers', to='contacts.address'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier_primary_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='primary_for_suppliers', to='contacts.contact'),
        ),
    ]
