# Generated by Django 5.2.17 on 2026-09-28 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('name', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('abbr', models.CharField(blank=True, max_length=140, unique=True)),
                ('is_group', models.BooleanField(default=False)),
                ('valuation_method', models.CharField(choices=[('FIFO', 'FIFO'), ('Moving Average', 'Moving Average'), ('LIFO', 'LIFO')], default='FIFO', max_length=20)),
                ('tax_id', models.CharField(blank=True, max_length=140)),
                ('date_of_establishment', models.DateField(blank=True, null=True)),
                ('date_of_incorporation', models.DateField(blank=True, null=True)),
                ('date_of_commencement', models.DateField(blank=True, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=140)),
                ('fax', models.CharField(blank=True, max_length=140)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.CharField(blank=True, max_length=140)),
                ('company_description', models.TextField(blank=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='geo.country')),
                ('default_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='default_for_companies', to='geo.currency')),
                ('parent_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='organizations.company')),
                ('reporting_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reporting_for_companies', to='geo.currency')),
            ],
            options={
                'verbose_name_plural': 'companies',
                'db_table': 'company',
            },
        ),
    ]
