# Generated by Django 5.2.17 on 2026-09-28 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_remove_partyaccount_party_account_one_party_and_more'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='default_advance_paid_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_advance_paid_for_companies', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='company',
            name='default_advance_received_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_advance_received_for_companies', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='company',
            name='default_payable_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_payable_for_companies', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='company',
            name='default_receivable_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_receivable_for_companies', to='accounting.account'),
        ),
    ]
