# Generated by Django 5.2.17 on 2026-09-28 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_costcenter_glentry_cost_center_and_more'),
        ('organizations', '0002_company_default_advance_paid_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_for_companies', to='accounting.costcenter'),
        ),
    ]
