# Generated by Django 5.2.17 on 2026-09-29 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_financebook_alter_accountclosingbalance_options_and_more'),
        ('organizations', '0003_company_cost_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='default_finance_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_for_companies', to='accounting.financebook'),
        ),
    ]
