# Generated by Django 5.2.17 on 2026-09-29 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_alter_accountclosingbalance_options_and_more'),
        ('organizations', '0005_company_inventory_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='stock_adjustment_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_adjustment_for_companies', to='accounting.account'),
        ),
    ]
