# Generated by Django 5.2.17 on 2026-10-06 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_company_stock_adjustment_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='chart_of_accounts',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='company',
            name='create_chart_of_accounts_based_on',
            field=models.CharField(blank=True, choices=[('Standard Template', 'Standard Template'), ('Existing Company', 'Existing Company')], max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='existing_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='descendant_chart_companies', to='organizations.company'),
        ),
    ]
