# Generated by Django 5.2.17 on 2026-09-28 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UOMCategory',
            fields=[
                ('name', models.CharField(max_length=140, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'UOM category',
                'verbose_name_plural': 'UOM categories',
                'db_table': 'uom_category',
            },
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('name', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('symbol', models.CharField(blank=True, max_length=140)),
                ('common_code', models.CharField(blank=True, max_length=3)),
                ('description', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
                ('must_be_whole_number', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='catalog.uomcategory')),
            ],
            options={
                'verbose_name': 'unit of measure',
                'verbose_name_plural': 'units of measure',
                'db_table': 'uom',
            },
        ),
    ]
