# Generated by Django 5.2.17 on 2026-09-28 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemGroup',
            fields=[
                ('name', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('is_group', models.BooleanField(default=False)),
                ('image', models.CharField(blank=True, max_length=512)),
                ('lft', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('rgt', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('parent_item_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='catalog.itemgroup')),
            ],
            options={
                'db_table': 'item_group',
                'ordering': ('lft', 'name'),
            },
        ),
    ]
