# Generated by Django 5.2.17 on 2026-09-28 07:56

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_itemgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('name', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('item_name', models.CharField(blank=True, max_length=140)),
                ('disabled', models.BooleanField(default=False)),
                ('is_stock_item', models.BooleanField(default=True)),
                ('is_purchase_item', models.BooleanField(default=True)),
                ('is_sales_item', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.CharField(blank=True, max_length=512)),
                ('end_of_life', models.DateField(default=datetime.date(2099, 12, 31))),
                ('item_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='catalog.itemgroup')),
                ('stock_uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_items', to='catalog.unitofmeasure')),
            ],
            options={
                'db_table': 'item',
            },
        ),
    ]
