# Generated by Django 5.2.17 on 2026-09-28 08:00

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemUOMConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversion_factor', models.DecimalField(decimal_places=9, default=Decimal('0'), max_digits=21, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uom_conversions', to='catalog.item')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_conversions', to='catalog.unitofmeasure')),
            ],
            options={
                'db_table': 'uom_conversion_detail',
                'ordering': ('id',),
                'constraints': [models.UniqueConstraint(fields=('item', 'uom'), name='unique_item_uom_conversion')],
            },
        ),
    ]
