# Generated by Django 5.2.17 on 2026-09-28 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_backfill_stock_uom_conversions'),
    ]

    operations = [
        migrations.CreateModel(
            name='UOMConversionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=15, max_digits=30)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='global_conversions', to='catalog.uomcategory')),
                ('from_uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversions_from', to='catalog.unitofmeasure')),
                ('to_uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversions_to', to='catalog.unitofmeasure')),
            ],
            options={
                'db_table': 'uom_conversion_factor',
                'ordering': ('id',),
            },
        ),
    ]
