# Generated by Django 5.2.17 on 2026-09-28 08:16

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_uomconversionfactor'),
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('name', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=True)),
                ('buying', models.BooleanField(default=False)),
                ('selling', models.BooleanField(default=False)),
                ('price_not_uom_dependent', models.BooleanField(default=False)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_lists', to='geo.currency')),
            ],
            options={
                'db_table': 'price_list',
            },
        ),
        migrations.CreateModel(
            name='ItemPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packing_unit', models.IntegerField(default=0)),
                ('item_name', models.CharField(blank=True, editable=False, max_length=140)),
                ('item_description', models.TextField(blank=True, editable=False)),
                ('buying', models.BooleanField(default=False, editable=False)),
                ('selling', models.BooleanField(default=False, editable=False)),
                ('price_list_rate', models.DecimalField(decimal_places=9, max_digits=30)),
                ('valid_from', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('valid_upto', models.DateField(blank=True, null=True)),
                ('customer', models.CharField(blank=True, max_length=140)),
                ('supplier', models.CharField(blank=True, max_length=140)),
                ('batch_no', models.CharField(blank=True, max_length=140)),
                ('lead_time_days', models.IntegerField(default=0)),
                ('note', models.TextField(blank=True)),
                ('reference', models.CharField(blank=True, max_length=140)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_prices', to='geo.currency')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prices', to='catalog.item')),
                ('uom', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='item_prices', to='catalog.unitofmeasure')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_prices', to='catalog.pricelist')),
            ],
            options={
                'db_table': 'item_price',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='PriceListCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_lists', to='geo.country')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='catalog.pricelist')),
            ],
            options={
                'db_table': 'price_list_country',
                'constraints': [models.UniqueConstraint(fields=('price_list', 'country'), name='unique_price_list_country')],
            },
        ),
    ]
