# Generated by Django 5.2.17 on 2026-09-28 10:18

import django.db.models.deletion
from django.db import migrations, models


def copy_names_to_legacy(apps, schema_editor):
    ItemPrice = apps.get_model("catalog", "ItemPrice")
    for row in ItemPrice.objects.using(schema_editor.connection.alias).values("pk", "customer", "supplier").iterator():
        ItemPrice.objects.using(schema_editor.connection.alias).filter(pk=row["pk"]).update(
            legacy_customer_name=row["customer"] or "",
            legacy_supplier_name=row["supplier"] or "",
        )


def restore_names_from_legacy(apps, schema_editor):
    ItemPrice = apps.get_model("catalog", "ItemPrice")
    for row in ItemPrice.objects.using(schema_editor.connection.alias).values(
        "pk", "legacy_customer_name", "legacy_supplier_name"
    ).iterator():
        ItemPrice.objects.using(schema_editor.connection.alias).filter(pk=row["pk"]).update(
            customer=row["legacy_customer_name"],
            supplier=row["legacy_supplier_name"],
        )


def link_existing_parties(apps, schema_editor):
    ItemPrice = apps.get_model("catalog", "ItemPrice")
    Customer = apps.get_model("parties", "Customer")
    Supplier = apps.get_model("parties", "Supplier")
    db = schema_editor.connection.alias
    for row in ItemPrice.objects.using(db).values(
        "pk", "legacy_customer_name", "legacy_supplier_name"
    ).iterator():
        updates = {}
        customer_name = row["legacy_customer_name"]
        supplier_name = row["legacy_supplier_name"]
        if customer_name and Customer.objects.using(db).filter(pk=customer_name).exists():
            updates.update(customer_id=customer_name, legacy_customer_name="")
        if supplier_name and Supplier.objects.using(db).filter(pk=supplier_name).exists():
            updates.update(supplier_id=supplier_name, legacy_supplier_name="")
        if updates:
            ItemPrice.objects.using(db).filter(pk=row["pk"]).update(**updates)


def restore_linked_names(apps, schema_editor):
    ItemPrice = apps.get_model("catalog", "ItemPrice")
    db = schema_editor.connection.alias
    for row in ItemPrice.objects.using(db).values("pk", "customer_id", "supplier_id").iterator():
        updates = {}
        if row["customer_id"]:
            updates["legacy_customer_name"] = row["customer_id"]
        if row["supplier_id"]:
            updates["legacy_supplier_name"] = row["supplier_id"]
        if updates:
            ItemPrice.objects.using(db).filter(pk=row["pk"]).update(**updates)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_pricelist_itemprice_pricelistcountry'),
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemprice',
            name='legacy_customer_name',
            field=models.CharField(blank=True, editable=False, max_length=140),
        ),
        migrations.AddField(
            model_name='itemprice',
            name='legacy_supplier_name',
            field=models.CharField(blank=True, editable=False, max_length=140),
        ),
        migrations.RunPython(copy_names_to_legacy, restore_names_from_legacy),
        migrations.RemoveField(model_name='itemprice', name='customer'),
        migrations.RemoveField(model_name='itemprice', name='supplier'),
        migrations.AddField(
            model_name='itemprice',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item_prices', to='parties.customer'),
        ),
        migrations.AddField(
            model_name='itemprice',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item_prices', to='parties.supplier'),
        ),
        migrations.RunPython(link_existing_parties, restore_linked_names),
    ]
