# Generated by Django 5.2.17 on 2026-09-30 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_itemprice_legacy_customer_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('name', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('image', models.CharField(blank=True, max_length=512)),
            ],
            options={
                'db_table': 'brand',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='item',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='catalog.brand'),
        ),
    ]
