# Generated by Django 5.2.17 on 2026-09-28 07:26

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('name', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=2)),
                ('date_format', models.CharField(blank=True, max_length=140)),
                ('time_format', models.CharField(default='HH:mm:ss', max_length=140)),
                ('time_zones', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'countries',
                'db_table': 'country',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('name', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=False)),
                ('fraction', models.CharField(blank=True, max_length=140)),
                ('fraction_units', models.IntegerField(default=0)),
                ('smallest_currency_fraction_value', models.DecimalField(decimal_places=9, default=Decimal('0'), max_digits=21, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('symbol', models.CharField(blank=True, max_length=140)),
                ('symbol_on_right', models.BooleanField(default=False)),
                ('number_format', models.CharField(blank=True, choices=[('#,###.##', '#,###.##'), ('#.###,##', '#.###,##'), ('# ###.##', '# ###.##'), ('# ###,##', '# ###,##'), ("#'###.##", "#'###.##"), ('#, ###.##', '#, ###.##'), ('#,##,###.##', '#,##,###.##'), ('#,###.###', '#,###.###'), ('#.###', '#.###'), ('#,###', '#,###')], max_length=20)),
            ],
            options={
                'verbose_name_plural': 'currencies',
                'db_table': 'currency',
            },
        ),
    ]
