# Generated by Django 5.2.17 on 2026-09-28 13:00

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyExchange',
            fields=[
                ('name', models.CharField(blank=True, editable=False, max_length=140, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('exchange_rate', models.DecimalField(decimal_places=9, max_digits=21, validators=[django.core.validators.MinValueValidator(Decimal('1E-9'))])),
                ('for_buying', models.BooleanField(default=True)),
                ('for_selling', models.BooleanField(default=True)),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchange_rates_from', to='geo.currency')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchange_rates_to', to='geo.currency')),
            ],
            options={
                'db_table': 'currency_exchange',
                'ordering': ('-date', '-name'),
                'constraints': [models.UniqueConstraint(fields=('date', 'from_currency', 'to_currency', 'for_buying', 'for_selling'), name='unique_currency_exchange_purpose'), models.CheckConstraint(condition=models.Q(('from_currency', models.F('to_currency')), _negated=True), name='currency_exchange_different_currencies'), models.CheckConstraint(condition=models.Q(('for_buying', True), ('for_selling', True), _connector='OR'), name='currency_exchange_has_purpose'), models.CheckConstraint(condition=models.Q(('exchange_rate__gt', 0)), name='currency_exchange_positive_rate')],
            },
        ),
    ]
