from django.urls import path
from . import views

app_name = "demo"
urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("workspace/", views.workspace, name="workspace"),
    path("customers/", views.customers, name="customers"),
    path("customers/new/", views.customer_new, name="customer_new"),
    path("customers/<int:pk>/", views.customer_detail, name="customer_detail"),
    path("customers/<int:pk>/edit/", views.customer_edit, name="customer_edit"),
    path("customers/<int:pk>/toggle/", views.customer_toggle, name="customer_toggle"),
    path("suppliers/", views.suppliers, name="suppliers"),
    path("suppliers/new/", views.supplier_new, name="supplier_new"),
    path("suppliers/<int:pk>/", views.supplier_detail, name="supplier_detail"),
    path("suppliers/<int:pk>/edit/", views.supplier_edit, name="supplier_edit"),
    path("suppliers/<int:pk>/toggle/", views.supplier_toggle, name="supplier_toggle"),
    path("items/", views.items, name="items"),
    path("items/new/", views.item_new, name="item_new"),
    path("items/<int:pk>/", views.item_detail, name="item_detail"),
    path("items/<int:pk>/edit/", views.item_edit, name="item_edit"),
    path("items/<int:pk>/toggle/", views.item_toggle, name="item_toggle"),
    path("products/tree/", views.product_tree, name="product_tree"),
    path("products/tree/<int:pk>/", views.product_tree, name="product_tree_detail"),
    path("boms/", views.bom_versions, name="bom_versions"),
    path("boms/new/", views.bom_new, name="bom_new"),
    path("boms/<int:pk>/edit/", views.bom_edit, name="bom_edit"),
    path("boms/<int:pk>/clone/", views.bom_clone, name="bom_clone"),
    path("boms/<int:pk>/activate/", views.bom_activate, name="bom_activate"),
    path("orders/<str:kind>/", views.orders, name="orders"),
    path("orders/<str:kind>/new/", views.order_new, name="order_new"),
    path("purchasing/recommendations/", views.purchase_recommendations, name="purchase_recommendations"),
    path("orders/<int:pk>/detail/", views.order_detail, name="order_detail"),
    path("orders/<int:pk>/edit/", views.order_edit, name="order_edit"),
    path("orders/<int:pk>/confirm/", views.order_confirm, name="order_confirm"),
    path("orders/<int:pk>/fulfill/", views.order_fulfill, name="order_fulfill"),
    path("orders/<int:pk>/invoice/", views.order_issue_invoice, name="order_issue_invoice"),
    path("orders/<int:pk>/payment/", views.order_payment, name="order_payment"),
    path("orders/<int:pk>/cancel/", views.order_cancel, name="order_cancel"),
    path("invoices/<int:pk>/print/", views.invoice_print, name="invoice_print"),
    path("inventory/", views.inventory, name="inventory"),
    path("inventory/items/<int:pk>/", views.item_ledger, name="item_ledger"),
    path("inventory/items/<int:pk>/adjust/", views.item_adjust, name="item_adjust"),
    path("reports/", views.reports, name="reports"),
    path("audit/", views.audit_events, name="audit_events"),
    path("scope/", views.product_scope, name="product_scope"),
    path("decisions/", views.management_decisions, name="management_decisions"),
    path("decisions/new/", views.management_decision_edit, name="management_decision_new"),
    path("decisions/<int:pk>/edit/", views.management_decision_edit, name="management_decision_edit"),
    path("decisions/<int:decision_pk>/fit-gap/", views.decision_fit_gap, name="decision_fit_gap"),
    path("decisions/<int:decision_pk>/fit-gap/new/", views.fit_gap_edit, name="fit_gap_new"),
    path("decisions/<int:decision_pk>/fit-gap/<int:pk>/edit/", views.fit_gap_edit,
         name="fit_gap_edit"),
    path("decisions/<int:decision_pk>/fit-gap.csv", views.decision_fit_gap_csv,
         name="decision_fit_gap_csv"),
]

