# Generated by Django 5.2.17 on 2026-09-29 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0004_company_default_finance_book'),
        ('parties', '0002_customer_customer_primary_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('name', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=140, unique=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('On hold', 'On hold'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Open', max_length=12)),
                ('is_active', models.BooleanField(default=True)),
                ('expected_start_date', models.DateField(blank=True, null=True)),
                ('expected_end_date', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='organizations.company')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='parties.customer')),
            ],
            options={
                'db_table': 'project',
                'ordering': ('project_name', 'name'),
            },
        ),
    ]
