# Generated by Django 5.2.17 on 2026-09-28 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('name', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('address_title', models.CharField(blank=True, max_length=140)),
                ('address_type', models.CharField(choices=[('Billing', 'Billing'), ('Shipping', 'Shipping'), ('Office', 'Office'), ('Personal', 'Personal'), ('Plant', 'Plant'), ('Postal', 'Postal'), ('Shop', 'Shop'), ('Subsidiary', 'Subsidiary'), ('Warehouse', 'Warehouse'), ('Current', 'Current'), ('Permanent', 'Permanent'), ('Other', 'Other')], max_length=20)),
                ('address_line1', models.CharField(max_length=240)),
                ('address_line2', models.CharField(blank=True, max_length=240)),
                ('city', models.CharField(max_length=140)),
                ('county', models.CharField(blank=True, max_length=140)),
                ('state', models.CharField(blank=True, max_length=140)),
                ('pincode', models.CharField(blank=True, max_length=140)),
                ('email_id', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=140)),
                ('fax', models.CharField(blank=True, max_length=140)),
                ('is_primary_address', models.BooleanField(default=False)),
                ('is_shipping_address', models.BooleanField(default=False)),
                ('disabled', models.BooleanField(default=False)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='geo.country')),
            ],
            options={
                'verbose_name_plural': 'addresses',
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('name', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=140)),
                ('middle_name', models.CharField(blank=True, max_length=140)),
                ('last_name', models.CharField(blank=True, max_length=140)),
                ('status', models.CharField(choices=[('Passive', 'Passive'), ('Open', 'Open'), ('Replied', 'Replied')], default='Passive', max_length=10)),
                ('designation', models.CharField(blank=True, max_length=140)),
                ('department', models.CharField(blank=True, max_length=140)),
                ('is_primary_contact', models.BooleanField(default=False)),
                ('unsubscribed', models.BooleanField(default=False)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='contacts.address')),
            ],
            options={
                'db_table': 'contact',
            },
        ),
        migrations.CreateModel(
            name='AddressPartyLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_links', to='contacts.address')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parties.customer')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parties.supplier')),
            ],
            options={
                'db_table': 'address_party_link',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('customer__isnull', False), ('supplier__isnull', True)), models.Q(('customer__isnull', True), ('supplier__isnull', False)), _connector='OR'), name='address_link_one_party'), models.UniqueConstraint(condition=models.Q(('customer__isnull', False)), fields=('address', 'customer'), name='unique_address_customer'), models.UniqueConstraint(condition=models.Q(('supplier__isnull', False)), fields=('address', 'supplier'), name='unique_address_supplier')],
            },
        ),
        migrations.CreateModel(
            name='ContactEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.EmailField(max_length=254)),
                ('is_primary', models.BooleanField(default=False)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_ids', to='contacts.contact')),
            ],
            options={
                'db_table': 'contact_email',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('contact',), name='one_primary_email_per_contact')],
            },
        ),
        migrations.CreateModel(
            name='ContactPartyLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_links', to='contacts.contact')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parties.customer')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parties.supplier')),
            ],
            options={
                'db_table': 'contact_party_link',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('customer__isnull', False), ('supplier__isnull', True)), models.Q(('customer__isnull', True), ('supplier__isnull', False)), _connector='OR'), name='contact_link_one_party'), models.UniqueConstraint(condition=models.Q(('customer__isnull', False)), fields=('contact', 'customer'), name='unique_contact_customer'), models.UniqueConstraint(condition=models.Q(('supplier__isnull', False)), fields=('contact', 'supplier'), name='unique_contact_supplier')],
            },
        ),
        migrations.CreateModel(
            name='ContactPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=140)),
                ('is_primary_phone', models.BooleanField(default=False)),
                ('is_primary_mobile_no', models.BooleanField(default=False)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_nos', to='contacts.contact')),
            ],
            options={
                'db_table': 'contact_phone',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary_phone', True)), fields=('contact',), name='one_primary_phone_per_contact'), models.UniqueConstraint(condition=models.Q(('is_primary_mobile_no', True)), fields=('contact',), name='one_primary_mobile_per_contact')],
            },
        ),
    ]
