# Generated by Django 5.2.17 on 2026-09-28 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
        ('organizations', '0001_initial'),
        ('parties', '0002_customer_customer_primary_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('name', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('account_name', models.CharField(max_length=140)),
                ('account_number', models.CharField(blank=True, max_length=140)),
                ('is_group', models.BooleanField(default=False)),
                ('root_type', models.CharField(blank=True, choices=[('Asset', 'Asset'), ('Liability', 'Liability'), ('Income', 'Income'), ('Expense', 'Expense'), ('Equity', 'Equity')], max_length=10)),
                ('report_type', models.CharField(blank=True, choices=[('Balance Sheet', 'Balance Sheet'), ('Profit and Loss', 'Profit and Loss')], max_length=20)),
                ('account_type', models.CharField(blank=True, max_length=140)),
                ('disabled', models.BooleanField(default=False)),
                ('lft', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('rgt', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('account_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='geo.currency')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='organizations.company')),
                ('parent_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='accounting.account')),
            ],
            options={
                'db_table': 'account',
                'ordering': ('company', 'lft', 'name'),
            },
        ),
        migrations.CreateModel(
            name='PartyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='party_defaults', to='accounting.account')),
                ('advance_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='party_advance_defaults', to='accounting.account')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='party_accounts', to='organizations.company')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='parties.customer')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='parties.supplier')),
            ],
            options={
                'db_table': 'party_account',
            },
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(condition=models.Q(('account_number', ''), _negated=True), fields=('company', 'account_number'), name='unique_account_number_per_company'),
        ),
        migrations.AddConstraint(
            model_name='partyaccount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('customer__isnull', False), ('supplier__isnull', True)), models.Q(('customer__isnull', True), ('supplier__isnull', False)), _connector='OR'), name='party_account_one_party'),
        ),
        migrations.AddConstraint(
            model_name='partyaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('customer__isnull', False)), fields=('customer', 'company'), name='unique_customer_account_per_company'),
        ),
        migrations.AddConstraint(
            model_name='partyaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('supplier__isnull', False)), fields=('supplier', 'company'), name='unique_supplier_account_per_company'),
        ),
    ]
