# Generated by Django 5.2.17 on 2026-09-28 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('organizations', '0001_initial'),
        ('parties', '0002_customer_customer_primary_address_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='partyaccount',
            name='party_account_one_party',
        ),
        migrations.AddField(
            model_name='partyaccount',
            name='customer_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='parties.customergroup'),
        ),
        migrations.AddField(
            model_name='partyaccount',
            name='supplier_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='parties.suppliergroup'),
        ),
        migrations.AddConstraint(
            model_name='partyaccount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('customer__isnull', False), ('customer_group__isnull', True), ('supplier__isnull', True), ('supplier_group__isnull', True)), models.Q(('customer__isnull', True), ('customer_group__isnull', True), ('supplier__isnull', False), ('supplier_group__isnull', True)), models.Q(('customer__isnull', True), ('customer_group__isnull', False), ('supplier__isnull', True), ('supplier_group__isnull', True)), models.Q(('customer__isnull', True), ('customer_group__isnull', True), ('supplier__isnull', True), ('supplier_group__isnull', False)), _connector='OR'), name='party_account_one_party'),
        ),
        migrations.AddConstraint(
            model_name='partyaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('customer_group__isnull', False)), fields=('customer_group', 'company'), name='unique_customer_group_account_per_company'),
        ),
        migrations.AddConstraint(
            model_name='partyaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('supplier_group__isnull', False)), fields=('supplier_group', 'company'), name='unique_supplier_group_account_per_company'),
        ),
    ]
