# Generated by Django 5.2.17 on 2026-09-28 12:39

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_remove_partyaccount_party_account_one_party_and_more'),
        ('geo', '0001_initial'),
        ('organizations', '0002_company_default_advance_paid_account_and_more'),
        ('parties', '0002_customer_customer_primary_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GLEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posting_date', models.DateField(db_index=True)),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('voucher_type', models.CharField(max_length=140)),
                ('voucher_no', models.CharField(max_length=140)),
                ('debit', models.DecimalField(decimal_places=9, default=Decimal('0'), max_digits=21)),
                ('credit', models.DecimalField(decimal_places=9, default=Decimal('0'), max_digits=21)),
                ('debit_in_account_currency', models.DecimalField(decimal_places=9, default=Decimal('0'), max_digits=21)),
                ('credit_in_account_currency', models.DecimalField(decimal_places=9, default=Decimal('0'), max_digits=21)),
                ('is_opening', models.BooleanField(default=False)),
                ('is_advance', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('against', models.TextField(blank=True)),
                ('against_voucher_type', models.CharField(blank=True, max_length=140)),
                ('against_voucher', models.CharField(blank=True, max_length=140)),
                ('remarks', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gl_entries', to='accounting.account')),
                ('account_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gl_entries', to='geo.currency')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gl_entries', to='organizations.company')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gl_entries', to='parties.customer')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gl_entries', to='parties.supplier')),
            ],
            options={
                'db_table': 'gl_entry',
                'ordering': ('posting_date', 'id'),
                'indexes': [models.Index(fields=['company', 'posting_date'], name='gl_company_date_idx'), models.Index(fields=['company', 'voucher_type', 'voucher_no'], name='gl_voucher_idx'), models.Index(fields=['account', 'posting_date'], name='gl_account_date_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('credit', 0), ('debit__gt', 0)), models.Q(('credit__gt', 0), ('debit', 0)), _connector='OR'), name='gl_one_positive_side')],
            },
        ),
    ]
