# Generated by Django 5.2.17 on 2026-09-28 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_glentry'),
        ('organizations', '0002_company_default_advance_paid_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('name', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('cost_center_name', models.CharField(max_length=140)),
                ('cost_center_number', models.CharField(blank=True, max_length=140)),
                ('is_group', models.BooleanField(default=False)),
                ('disabled', models.BooleanField(default=False)),
                ('lft', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('rgt', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_centers', to='organizations.company')),
                ('parent_cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='accounting.costcenter')),
            ],
            options={
                'db_table': 'cost_center',
                'ordering': ('company', 'lft', 'name'),
            },
        ),
        migrations.AddField(
            model_name='glentry',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gl_entries', to='accounting.costcenter'),
        ),
        migrations.AddConstraint(
            model_name='costcenter',
            constraint=models.UniqueConstraint(condition=models.Q(('cost_center_number', ''), _negated=True), fields=('company', 'cost_center_number'), name='unique_cost_center_number_per_company'),
        ),
    ]
