# Generated by Django 5.2.17 on 2026-09-28 13:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_costcenter_glentry_cost_center_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='glentry',
            name='account_exchange_rate',
            field=models.DecimalField(decimal_places=9, default=Decimal('1'), max_digits=21),
        ),
    ]
