# Generated by Django 5.2.17 on 2026-09-28 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_glentry_account_exchange_rate'),
        ('organizations', '0003_company_cost_center'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('year', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('year_start_date', models.DateField()),
                ('year_end_date', models.DateField()),
                ('disabled', models.BooleanField(default=False)),
                ('is_short_year', models.BooleanField(default=False)),
                ('auto_created', models.BooleanField(default=False)),
                ('all_companies', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'fiscal_year',
                'ordering': ('-year_start_date', 'year'),
            },
        ),
        migrations.AddField(
            model_name='glentry',
            name='fiscal_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gl_entries', to='accounting.fiscalyear'),
        ),
        migrations.CreateModel(
            name='FiscalYearCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_year_links', to='organizations.company')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_links', to='accounting.fiscalyear')),
            ],
            options={
                'db_table': 'fiscal_year_company',
            },
        ),
        migrations.AddField(
            model_name='fiscalyear',
            name='companies',
            field=models.ManyToManyField(blank=True, related_name='fiscal_years', through='accounting.FiscalYearCompany', to='organizations.company'),
        ),
        migrations.AddConstraint(
            model_name='fiscalyearcompany',
            constraint=models.UniqueConstraint(fields=('fiscal_year', 'company'), name='unique_fiscal_year_company'),
        ),
    ]
