# Generated by Django 5.2.17 on 2026-09-28 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_fiscalyear_glentry_fiscal_year_fiscalyearcompany_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('organizations', '0003_company_cost_center'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingPeriod',
            fields=[
                ('name', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('period_name', models.CharField(max_length=140, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('disabled', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounting_periods', to='organizations.company')),
                ('exempted_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exempted_accounting_periods', to='auth.group')),
            ],
            options={
                'db_table': 'accounting_period',
                'ordering': ('-start_date', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ClosedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=140)),
                ('closed', models.BooleanField(default=False)),
                ('accounting_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closed_documents', to='accounting.accountingperiod')),
            ],
            options={
                'db_table': 'closed_document',
                'ordering': ('document_type',),
            },
        ),
        migrations.AddIndex(
            model_name='accountingperiod',
            index=models.Index(fields=['company', 'start_date', 'end_date'], name='acct_period_company_dates'),
        ),
        migrations.AddConstraint(
            model_name='closeddocument',
            constraint=models.UniqueConstraint(fields=('accounting_period', 'document_type'), name='unique_closed_document_per_period'),
        ),
    ]
