# Generated by Django 5.2.17 on 2026-09-28 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_accountingperiod_closeddocument_and_more'),
        ('organizations', '0003_company_cost_center'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodClosingVoucher',
            fields=[
                ('name', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('period_start_date', models.DateField()),
                ('period_end_date', models.DateField()),
                ('remarks', models.TextField()),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted')], default='Draft', editable=False, max_length=12)),
                ('closing_account_head', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='period_closing_vouchers', to='accounting.account')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='period_closing_vouchers', to='organizations.company')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='period_closing_vouchers', to='accounting.fiscalyear')),
            ],
            options={
                'db_table': 'period_closing_voucher',
                'ordering': ('company', 'period_end_date', 'name'),
                'indexes': [models.Index(fields=['company', 'period_end_date'], name='pcv_company_end_idx')],
            },
        ),
    ]
