# Generated by Django 5.2.17 on 2026-09-29 06:47

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_periodclosingvoucher'),
        ('geo', '0002_currencyexchange'),
        ('organizations', '0003_company_cost_center'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountClosingBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closing_date', models.DateField(db_index=True)),
                ('is_period_closing_voucher_entry', models.BooleanField(default=False)),
                ('debit', models.DecimalField(decimal_places=9, default=Decimal('0'), max_digits=21)),
                ('credit', models.DecimalField(decimal_places=9, default=Decimal('0'), max_digits=21)),
                ('debit_in_account_currency', models.DecimalField(decimal_places=9, default=Decimal('0'), max_digits=21)),
                ('credit_in_account_currency', models.DecimalField(decimal_places=9, default=Decimal('0'), max_digits=21)),
                ('reporting_currency_exchange_rate', models.DecimalField(decimal_places=9, default=Decimal('1'), max_digits=21)),
                ('debit_in_reporting_currency', models.DecimalField(decimal_places=9, default=Decimal('0'), max_digits=21)),
                ('credit_in_reporting_currency', models.DecimalField(decimal_places=9, default=Decimal('0'), max_digits=21)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='closing_balances', to='accounting.account')),
                ('account_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_closing_balances', to='geo.currency')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_closing_balances', to='organizations.company')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closing_balances', to='accounting.costcenter')),
                ('period_closing_voucher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='closing_balances', to='accounting.periodclosingvoucher')),
            ],
            options={
                'db_table': 'account_closing_balance',
                'ordering': ('company', 'closing_date', 'account', 'cost_center', 'is_period_closing_voucher_entry'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('cost_center__isnull', True)), fields=('period_closing_voucher', 'account', 'is_period_closing_voucher_entry'), name='unique_acb_without_center'), models.UniqueConstraint(condition=models.Q(('cost_center__isnull', False)), fields=('period_closing_voucher', 'account', 'cost_center', 'is_period_closing_voucher_entry'), name='unique_acb_with_center')],
            },
        ),
    ]
