# Generated by Django 5.2.17 on 2026-09-29 07:11

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_accountclosingbalance'),
        ('organizations', '0003_company_cost_center'),
        ('parties', '0002_customer_customer_primary_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('name', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('posting_date', models.DateField()),
                ('voucher_type', models.CharField(choices=[('Journal Entry', 'Journal Entry'), ('Opening Entry', 'Opening Entry')], default='Journal Entry', max_length=30)),
                ('multi_currency', models.BooleanField(default=False)),
                ('remark', models.TextField(blank=True)),
                ('total_debit', models.DecimalField(decimal_places=9, default=Decimal('0'), editable=False, max_digits=21)),
                ('total_credit', models.DecimalField(decimal_places=9, default=Decimal('0'), editable=False, max_digits=21)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted')], default='Draft', editable=False, max_length=12)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='organizations.company')),
            ],
            options={
                'db_table': 'journal_entry',
                'ordering': ('-posting_date', 'name'),
            },
        ),
        migrations.CreateModel(
            name='JournalEntryAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('debit_in_account_currency', models.DecimalField(decimal_places=9, default=Decimal('0'), max_digits=21)),
                ('credit_in_account_currency', models.DecimalField(decimal_places=9, default=Decimal('0'), max_digits=21)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=9, max_digits=21, null=True)),
                ('user_remark', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_rows', to='accounting.account')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_rows', to='accounting.costcenter')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_rows', to='parties.customer')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='accounting.journalentry')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_rows', to='parties.supplier')),
            ],
            options={
                'db_table': 'journal_entry_account',
                'ordering': ('journal_entry', 'position', 'id'),
                'constraints': [models.UniqueConstraint(fields=('journal_entry', 'position'), name='unique_journal_row_position'), models.CheckConstraint(condition=models.Q(models.Q(('credit_in_account_currency', 0), ('debit_in_account_currency__gt', 0)), models.Q(('credit_in_account_currency__gt', 0), ('debit_in_account_currency', 0)), _connector='OR'), name='journal_row_one_positive_side')],
            },
        ),
    ]
