# Generated by Django 5.2.17 on 2026-09-29 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_journalentry_journalentryaccount'),
        ('geo', '0002_currencyexchange'),
        ('organizations', '0003_company_cost_center'),
        ('parties', '0002_customer_customer_primary_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceBook',
            fields=[
                ('name', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('finance_book_name', models.CharField(max_length=140, unique=True)),
            ],
            options={
                'db_table': 'finance_book',
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='accountclosingbalance',
            options={'ordering': ('company', 'closing_date', 'account', 'cost_center', 'finance_book', 'is_period_closing_voucher_entry')},
        ),
        migrations.RemoveConstraint(
            model_name='accountclosingbalance',
            name='unique_acb_without_center',
        ),
        migrations.RemoveConstraint(
            model_name='accountclosingbalance',
            name='unique_acb_with_center',
        ),
        migrations.AddField(
            model_name='accountclosingbalance',
            name='finance_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closing_balances', to='accounting.financebook'),
        ),
        migrations.AddField(
            model_name='glentry',
            name='finance_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gl_entries', to='accounting.financebook'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='finance_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='accounting.financebook'),
        ),
        migrations.AddIndex(
            model_name='glentry',
            index=models.Index(fields=['company', 'finance_book', 'posting_date'], name='gl_company_book_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='accountclosingbalance',
            constraint=models.UniqueConstraint(condition=models.Q(('cost_center__isnull', True), ('finance_book__isnull', True)), fields=('period_closing_voucher', 'account', 'is_period_closing_voucher_entry'), name='acb_none_dimensions_uniq'),
        ),
        migrations.AddConstraint(
            model_name='accountclosingbalance',
            constraint=models.UniqueConstraint(condition=models.Q(('cost_center__isnull', False), ('finance_book__isnull', True)), fields=('period_closing_voucher', 'account', 'cost_center', 'is_period_closing_voucher_entry'), name='acb_center_only_uniq'),
        ),
        migrations.AddConstraint(
            model_name='accountclosingbalance',
            constraint=models.UniqueConstraint(condition=models.Q(('cost_center__isnull', True), ('finance_book__isnull', False)), fields=('period_closing_voucher', 'account', 'finance_book', 'is_period_closing_voucher_entry'), name='acb_book_only_uniq'),
        ),
        migrations.AddConstraint(
            model_name='accountclosingbalance',
            constraint=models.UniqueConstraint(condition=models.Q(('cost_center__isnull', False), ('finance_book__isnull', False)), fields=('period_closing_voucher', 'account', 'cost_center', 'finance_book', 'is_period_closing_voucher_entry'), name='acb_center_book_uniq'),
        ),
    ]
