# Generated by Django 5.2.17 on 2026-09-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_financebook_alter_accountclosingbalance_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentryaccount',
            name='reference_name',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='journalentryaccount',
            name='reference_type',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
