# Generated by Django 5.2.17 on 2026-09-29 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_journalentryaccount_reference_name_and_more'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='glentry',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gl_entries', to='projects.project'),
        ),
        migrations.AddField(
            model_name='journalentryaccount',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_rows', to='projects.project'),
        ),
    ]
