# Generated by Django 5.2.17 on 2026-09-29 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_glentry_project_journalentryaccount_project'),
        ('geo', '0002_currencyexchange'),
        ('organizations', '0004_company_default_finance_book'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountclosingbalance',
            options={'ordering': ('company', 'closing_date', 'account', 'cost_center', 'finance_book', 'project', 'is_period_closing_voucher_entry')},
        ),
        migrations.RemoveConstraint(
            model_name='accountclosingbalance',
            name='acb_none_dimensions_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='accountclosingbalance',
            name='acb_center_only_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='accountclosingbalance',
            name='acb_book_only_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='accountclosingbalance',
            name='acb_center_book_uniq',
        ),
        migrations.AddField(
            model_name='accountclosingbalance',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closing_balances', to='projects.project'),
        ),
        migrations.AddConstraint(
            model_name='accountclosingbalance',
            constraint=models.UniqueConstraint(condition=models.Q(('cost_center__isnull', True), ('finance_book__isnull', True), ('project__isnull', True)), fields=('period_closing_voucher', 'account', 'is_period_closing_voucher_entry'), name='acb_none_dimensions_uniq'),
        ),
        migrations.AddConstraint(
            model_name='accountclosingbalance',
            constraint=models.UniqueConstraint(condition=models.Q(('cost_center__isnull', False), ('finance_book__isnull', True), ('project__isnull', True)), fields=('period_closing_voucher', 'account', 'cost_center', 'is_period_closing_voucher_entry'), name='acb_center_only_uniq'),
        ),
        migrations.AddConstraint(
            model_name='accountclosingbalance',
            constraint=models.UniqueConstraint(condition=models.Q(('cost_center__isnull', True), ('finance_book__isnull', False), ('project__isnull', True)), fields=('period_closing_voucher', 'account', 'finance_book', 'is_period_closing_voucher_entry'), name='acb_book_only_uniq'),
        ),
        migrations.AddConstraint(
            model_name='accountclosingbalance',
            constraint=models.UniqueConstraint(condition=models.Q(('cost_center__isnull', False), ('finance_book__isnull', False), ('project__isnull', True)), fields=('period_closing_voucher', 'account', 'cost_center', 'finance_book', 'is_period_closing_voucher_entry'), name='acb_center_book_uniq'),
        ),
        migrations.AddConstraint(
            model_name='accountclosingbalance',
            constraint=models.UniqueConstraint(condition=models.Q(('cost_center__isnull', True), ('finance_book__isnull', True), ('project__isnull', False)), fields=('period_closing_voucher', 'account', 'project', 'is_period_closing_voucher_entry'), name='acb_project_only_uniq'),
        ),
        migrations.AddConstraint(
            model_name='accountclosingbalance',
            constraint=models.UniqueConstraint(condition=models.Q(('cost_center__isnull', False), ('finance_book__isnull', True), ('project__isnull', False)), fields=('period_closing_voucher', 'account', 'cost_center', 'project', 'is_period_closing_voucher_entry'), name='acb_center_project_uniq'),
        ),
        migrations.AddConstraint(
            model_name='accountclosingbalance',
            constraint=models.UniqueConstraint(condition=models.Q(('cost_center__isnull', True), ('finance_book__isnull', False), ('project__isnull', False)), fields=('period_closing_voucher', 'account', 'finance_book', 'project', 'is_period_closing_voucher_entry'), name='acb_book_project_uniq'),
        ),
        migrations.AddConstraint(
            model_name='accountclosingbalance',
            constraint=models.UniqueConstraint(condition=models.Q(('cost_center__isnull', False), ('finance_book__isnull', False), ('project__isnull', False)), fields=('period_closing_voucher', 'account', 'cost_center', 'finance_book', 'project', 'is_period_closing_voucher_entry'), name='acb_center_book_project_uniq'),
        ),
    ]
