# Generated by Django 5.2.17 on 2026-10-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_alter_accountclosingbalance_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='balance_must_be',
            field=models.CharField(blank=True, choices=[('Debit', 'Debit'), ('Credit', 'Credit')], max_length=10),
        ),
        migrations.AddField(
            model_name='account',
            name='freeze_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='include_in_gross',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='tax_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
