# Generated by Django 5.2.17 on 2026-10-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0015_account_balance_must_be_account_freeze_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodclosingvoucher',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Cancelled', 'Cancelled')], default='Draft', editable=False, max_length=12),
        ),
    ]
