# Generated by Django 5.2.17 on 2026-10-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0016_alter_periodclosingvoucher_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Cancelled', 'Cancelled')], default='Draft', editable=False, max_length=12),
        ),
    ]
