# Generated by Django 5.2.17 on 2026-09-29 21:49

import django.db.models.deletion
import stock.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_alter_accountclosingbalance_options_and_more'),
        ('catalog', '0008_itemprice_legacy_customer_name_and_more'),
        ('organizations', '0005_company_inventory_defaults'),
        ('projects', '0001_initial'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_qty', models.DecimalField(decimal_places=9, default=Decimal('0'), max_digits=30)),
                ('planned_qty', models.DecimalField(decimal_places=9, default=Decimal('0'), max_digits=30)),
                ('indented_qty', models.DecimalField(decimal_places=9, default=Decimal('0'), max_digits=30)),
                ('ordered_qty', models.DecimalField(decimal_places=9, default=Decimal('0'), max_digits=30)),
                ('reserved_qty', models.DecimalField(decimal_places=9, default=Decimal('0'), max_digits=30)),
                ('reserved_qty_for_production', models.DecimalField(decimal_places=9, default=Decimal('0'), max_digits=30)),
                ('reserved_qty_for_sub_contract', models.DecimalField(decimal_places=9, default=Decimal('0'), max_digits=30)),
                ('reserved_qty_for_production_plan', models.DecimalField(decimal_places=9, default=Decimal('0'), max_digits=30)),
                ('reserved_stock', models.DecimalField(decimal_places=9, default=Decimal('0'), max_digits=30)),
                ('projected_qty', models.DecimalField(decimal_places=9, default=Decimal('0'), max_digits=30)),
                ('valuation_rate', models.DecimalField(decimal_places=9, default=Decimal('0'), max_digits=30)),
                ('stock_value', models.DecimalField(decimal_places=9, default=Decimal('0'), max_digits=30)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_bins', to='organizations.company')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_bins', to='catalog.item')),
                ('stock_uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_bins', to='catalog.unitofmeasure')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bins', to='stock.warehouse')),
            ],
            options={
                'db_table': 'bin',
                'ordering': ('warehouse', 'item'),
            },
        ),
        migrations.CreateModel(
            name='StockLedgerEntry',
            fields=[
                ('name', models.CharField(default=stock.models.generate_stock_ledger_name, editable=False, max_length=140, primary_key=True, serialize=False)),
                ('posting_date', models.DateField(db_index=True)),
                ('posting_time', models.TimeField()),
                ('posting_datetime', models.DateTimeField(db_index=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('voucher_type', models.CharField(max_length=140)),
                ('voucher_no', models.CharField(max_length=140)),
                ('voucher_detail_no', models.CharField(blank=True, max_length=140)),
                ('actual_qty', models.DecimalField(decimal_places=9, max_digits=30)),
                ('qty_after_transaction', models.DecimalField(decimal_places=9, max_digits=30)),
                ('incoming_rate', models.DecimalField(decimal_places=9, default=Decimal('0'), max_digits=30)),
                ('outgoing_rate', models.DecimalField(decimal_places=9, default=Decimal('0'), max_digits=30)),
                ('valuation_rate', models.DecimalField(decimal_places=9, default=Decimal('0'), max_digits=30)),
                ('stock_value', models.DecimalField(decimal_places=9, default=Decimal('0'), max_digits=30)),
                ('stock_value_difference', models.DecimalField(decimal_places=9, default=Decimal('0'), max_digits=30)),
                ('stock_queue', models.JSONField(blank=True, default=list)),
                ('serial_no', models.TextField(blank=True)),
                ('batch_no', models.CharField(blank=True, max_length=140)),
                ('dependant_sle_voucher_detail_no', models.CharField(blank=True, max_length=140)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('is_adjustment_entry', models.BooleanField(default=False)),
                ('recalculate_rate', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_ledger_entries', to='organizations.company')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_ledger_entries', to='accounting.fiscalyear')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_ledger_entries', to='catalog.item')),
                ('item_bin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='stock.bin')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_ledger_entries', to='projects.project')),
                ('stock_uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_ledger_entries', to='catalog.unitofmeasure')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_ledger_entries', to='stock.warehouse')),
            ],
            options={
                'db_table': 'stock_ledger_entry',
                'ordering': ('posting_datetime', 'creation', 'name'),
            },
        ),
        migrations.AddConstraint(
            model_name='bin',
            constraint=models.UniqueConstraint(fields=('item', 'warehouse'), name='unique_bin_item_warehouse'),
        ),
        migrations.AddIndex(
            model_name='stockledgerentry',
            index=models.Index(fields=['item', 'warehouse', 'posting_datetime', 'name'], name='sle_item_wh_posting_idx'),
        ),
        migrations.AddIndex(
            model_name='stockledgerentry',
            index=models.Index(fields=['voucher_type', 'voucher_no'], name='sle_voucher_idx'),
        ),
        migrations.AddIndex(
            model_name='stockledgerentry',
            index=models.Index(fields=['company', 'posting_datetime'], name='sle_company_posting_idx'),
        ),
    ]
