# Generated by Django 5.2.17 on 2026-09-29 22:10

import django.db.models.deletion
import django.utils.timezone
import stock.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_itemprice_legacy_customer_name_and_more'),
        ('organizations', '0005_company_inventory_defaults'),
        ('projects', '0001_initial'),
        ('stock', '0002_bin_stockledgerentry_bin_unique_bin_item_warehouse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockEntryType',
            fields=[
                ('name', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('Material Issue', 'Material Issue'), ('Material Receipt', 'Material Receipt'), ('Material Transfer', 'Material Transfer'), ('Material Transfer for Manufacture', 'Material Transfer for Manufacture'), ('Material Consumption for Manufacture', 'Material Consumption for Manufacture'), ('Manufacture', 'Manufacture'), ('Repack', 'Repack'), ('Send to Subcontractor', 'Send to Subcontractor'), ('Disassemble', 'Disassemble'), ('Receive from Customer', 'Receive from Customer'), ('Return Raw Material to Customer', 'Return Raw Material to Customer'), ('Subcontracting Delivery', 'Subcontracting Delivery'), ('Subcontracting Return', 'Subcontracting Return')], max_length=50)),
                ('add_to_transit', models.BooleanField(default=False)),
                ('batch_split', models.BooleanField(default=False, editable=False)),
                ('is_standard', models.BooleanField(default=False, editable=False)),
            ],
            options={
                'db_table': 'stock_entry_type',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='StockEntry',
            fields=[
                ('name', models.CharField(default=stock.models.generate_stock_entry_name, editable=False, max_length=140, primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('Material Issue', 'Material Issue'), ('Material Receipt', 'Material Receipt'), ('Material Transfer', 'Material Transfer'), ('Material Transfer for Manufacture', 'Material Transfer for Manufacture'), ('Material Consumption for Manufacture', 'Material Consumption for Manufacture'), ('Manufacture', 'Manufacture'), ('Repack', 'Repack'), ('Send to Subcontractor', 'Send to Subcontractor'), ('Disassemble', 'Disassemble'), ('Receive from Customer', 'Receive from Customer'), ('Return Raw Material to Customer', 'Return Raw Material to Customer'), ('Subcontracting Delivery', 'Subcontracting Delivery'), ('Subcontracting Return', 'Subcontracting Return')], editable=False, max_length=50)),
                ('posting_date', models.DateField(default=django.utils.timezone.localdate)),
                ('posting_time', models.TimeField(default=stock.models.current_stock_time)),
                ('is_opening', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True)),
                ('total_incoming_value', models.DecimalField(decimal_places=9, default=Decimal('0'), editable=False, max_digits=30)),
                ('total_outgoing_value', models.DecimalField(decimal_places=9, default=Decimal('0'), editable=False, max_digits=30)),
                ('value_difference', models.DecimalField(decimal_places=9, default=Decimal('0'), editable=False, max_digits=30)),
                ('total_amount', models.DecimalField(decimal_places=9, default=Decimal('0'), editable=False, max_digits=30)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted')], default='Draft', editable=False, max_length=12)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_entries', to='organizations.company')),
                ('from_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_source_stock_entries', to='stock.warehouse')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_entries', to='projects.project')),
                ('to_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_target_stock_entries', to='stock.warehouse')),
                ('stock_entry_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_entries', to='stock.stockentrytype')),
            ],
            options={
                'db_table': 'stock_entry',
                'ordering': ('-posting_date', '-posting_time', 'name'),
            },
        ),
        migrations.CreateModel(
            name='StockEntryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('qty', models.DecimalField(decimal_places=9, max_digits=30)),
                ('conversion_factor', models.DecimalField(decimal_places=9, default=Decimal('1'), max_digits=30)),
                ('transfer_qty', models.DecimalField(decimal_places=9, default=Decimal('0'), editable=False, max_digits=30)),
                ('basic_rate', models.DecimalField(decimal_places=9, default=Decimal('0'), max_digits=30)),
                ('basic_amount', models.DecimalField(decimal_places=9, default=Decimal('0'), editable=False, max_digits=30)),
                ('amount', models.DecimalField(decimal_places=9, default=Decimal('0'), editable=False, max_digits=30)),
                ('valuation_rate', models.DecimalField(decimal_places=9, default=Decimal('0'), editable=False, max_digits=30)),
                ('allow_zero_valuation_rate', models.BooleanField(default=False)),
                ('actual_qty', models.DecimalField(decimal_places=9, default=Decimal('0'), editable=False, max_digits=30)),
                ('description', models.TextField(blank=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_entry_rows', to='catalog.item')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_entry_rows', to='projects.project')),
                ('source_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_stock_entry_rows', to='stock.warehouse')),
                ('stock_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stock.stockentry')),
                ('stock_uom', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='stock_entry_stock_rows', to='catalog.unitofmeasure')),
                ('target_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='target_stock_entry_rows', to='stock.warehouse')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_entry_rows', to='catalog.unitofmeasure')),
            ],
            options={
                'db_table': 'stock_entry_detail',
                'ordering': ('stock_entry', 'position', 'id'),
                'constraints': [models.UniqueConstraint(fields=('stock_entry', 'position'), name='unique_stock_entry_row_position')],
            },
        ),
        migrations.AddIndex(
            model_name='stockentry',
            index=models.Index(fields=['company', 'posting_date'], name='ste_company_date_idx'),
        ),
        migrations.AddIndex(
            model_name='stockentry',
            index=models.Index(fields=['company', 'status'], name='ste_company_status_idx'),
        ),
    ]
