# Generated by Django 5.2.17 on 2026-09-29 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_alter_accountclosingbalance_options_and_more'),
        ('stock', '0003_stockentrytype_stockentry_stockentrydetail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockentry',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_entries', to='accounting.costcenter'),
        ),
        migrations.AddField(
            model_name='stockentrydetail',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_entry_rows', to='accounting.costcenter'),
        ),
        migrations.AddField(
            model_name='stockentrydetail',
            name='expense_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_entry_rows', to='accounting.account'),
        ),
    ]
