# Generated by Django 5.2.17 on 2026-09-29 22:48

import django.db.models.deletion
from django.db import migrations, models


def backfill_submit_accounting_snapshot(apps, schema_editor):
    StockEntry = apps.get_model('stock', 'StockEntry')
    StockEntryDetail = apps.get_model('stock', 'StockEntryDetail')
    GLEntry = apps.get_model('accounting', 'GLEntry')
    alias = schema_editor.connection.alias
    for entry in StockEntry.objects.using(alias).filter(status='Submitted').select_related('company'):
        original_gl = list(GLEntry.objects.using(alias).filter(
            company_id=entry.company_id, voucher_type='Stock Entry', voucher_no=entry.pk,
        ).select_related('account'))
        # A historical zero-value or same-account movement has no GL to replay.
        # Do not infer its submit-time setting from today's company configuration.
        entry.perpetual_inventory_at_submit = bool(original_gl)
        entry.finance_book_id = (
            original_gl[0].finance_book_id if original_gl else entry.company.default_finance_book_id
        )
        entry.save(using=alias, update_fields=('perpetual_inventory_at_submit', 'finance_book'))
        difference_accounts = {
            row.account_id for row in original_gl if row.account.account_type != 'Stock'
        }
        centers = {row.cost_center_id for row in original_gl if row.cost_center_id}
        for detail in StockEntryDetail.objects.using(alias).filter(stock_entry_id=entry.pk):
            changes = []
            if detail.expense_account_id is None and len(difference_accounts) == 1:
                detail.expense_account_id = next(iter(difference_accounts))
                changes.append('expense_account')
            if detail.cost_center_id is None and len(centers) == 1:
                detail.cost_center_id = next(iter(centers))
                changes.append('cost_center')
            if changes:
                detail.save(using=alias, update_fields=changes)


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_alter_accountclosingbalance_options_and_more'),
        ('stock', '0004_stockentry_cost_center_stockentrydetail_cost_center_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockentry',
            name='finance_book',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_entries', to='accounting.financebook'),
        ),
        migrations.AddField(
            model_name='stockentry',
            name='perpetual_inventory_at_submit',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Cancelled', 'Cancelled')], default='Draft', editable=False, max_length=12),
        ),
        migrations.RunPython(backfill_submit_accounting_snapshot, migrations.RunPython.noop),
    ]
