# Generated by Django 5.2.17 on 2026-09-29 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_stockentry_finance_book_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptRateCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_rate', models.DecimalField(decimal_places=9, max_digits=30)),
                ('previous_rate', models.DecimalField(blank=True, decimal_places=9, editable=False, max_digits=30, null=True)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted')], default='Draft', editable=False, max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('stock_entry_detail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rate_corrections', to='stock.stockentrydetail')),
            ],
            options={
                'db_table': 'receipt_rate_correction',
                'ordering': ('-created_at', '-id'),
            },
        ),
    ]
