# Generated by Django 5.2.17 on 2026-09-29 23:19

import django.db.models.deletion
import django.utils.timezone
import stock.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_alter_accountclosingbalance_options_and_more'),
        ('catalog', '0008_itemprice_legacy_customer_name_and_more'),
        ('organizations', '0006_company_stock_adjustment_account'),
        ('stock', '0006_receiptratecorrection'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockReconciliation',
            fields=[
                ('name', models.CharField(default=stock.models.generate_stock_reconciliation_name, editable=False, max_length=140, primary_key=True, serialize=False)),
                ('posting_date', models.DateField(default=django.utils.timezone.localdate)),
                ('posting_time', models.TimeField(default=stock.models.current_stock_time)),
                ('remarks', models.TextField(blank=True)),
                ('total_increase_qty', models.DecimalField(decimal_places=9, default=Decimal('0'), editable=False, max_digits=30)),
                ('total_decrease_qty', models.DecimalField(decimal_places=9, default=Decimal('0'), editable=False, max_digits=30)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Cancelled', 'Cancelled')], default='Draft', editable=False, max_length=12)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_reconciliations', to='organizations.company')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_reconciliations', to='accounting.costcenter')),
                ('expense_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_reconciliations', to='accounting.account')),
                ('issue_entry', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations_as_issue', to='stock.stockentry')),
                ('receipt_entry', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations_as_receipt', to='stock.stockentry')),
            ],
            options={
                'db_table': 'stock_reconciliation',
                'ordering': ('-posting_date', '-posting_time', 'name'),
            },
        ),
        migrations.CreateModel(
            name='StockReconciliationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('counted_qty', models.DecimalField(decimal_places=9, max_digits=30)),
                ('receipt_rate', models.DecimalField(decimal_places=9, default=Decimal('0'), max_digits=30)),
                ('allow_zero_valuation_rate', models.BooleanField(default=False)),
                ('previous_qty', models.DecimalField(blank=True, decimal_places=9, editable=False, max_digits=30, null=True)),
                ('difference_qty', models.DecimalField(blank=True, decimal_places=9, editable=False, max_digits=30, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_reconciliation_rows', to='catalog.item')),
                ('reconciliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stock.stockreconciliation')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_reconciliation_rows', to='stock.warehouse')),
            ],
            options={
                'db_table': 'stock_reconciliation_item',
                'ordering': ('reconciliation', 'position', 'id'),
                'constraints': [models.UniqueConstraint(fields=('reconciliation', 'position'), name='unique_reco_row_position'), models.UniqueConstraint(fields=('reconciliation', 'item', 'warehouse'), name='unique_reco_item_warehouse')],
            },
        ),
    ]
