# Generated by Django 5.2.17 on 2026-09-29 23:28

from decimal import Decimal, ROUND_HALF_UP
from django.db import migrations, models


def backfill_reconciliation_values(apps, schema_editor):
    Reconciliation = apps.get_model('stock', 'StockReconciliation')
    Item = apps.get_model('stock', 'StockReconciliationItem')
    Ledger = apps.get_model('stock', 'StockLedgerEntry')
    alias = schema_editor.connection.alias
    quantum = Decimal('0.000000001')
    for document in Reconciliation.objects.using(alias).filter(status__in=('Submitted', 'Cancelled')):
        total = Decimal('0')
        for row in Item.objects.using(alias).filter(reconciliation_id=document.pk):
            if not row.difference_qty:
                Item.objects.using(alias).filter(pk=row.pk).update(value_difference=Decimal('0'))
                continue
            voucher_no = (
                document.receipt_entry_id if row.difference_qty > 0
                else document.issue_entry_id
            )
            sle = Ledger.objects.using(alias).filter(
                voucher_type='Stock Entry', voucher_no=voucher_no,
                item_id=row.item_id, warehouse_id=row.warehouse_id,
            ).first()
            if sle is None:
                continue
            previous_value = sle.stock_value - sle.stock_value_difference
            previous_rate = (
                (previous_value / row.previous_qty).quantize(quantum, rounding=ROUND_HALF_UP)
                if row.previous_qty else Decimal('0')
            )
            Item.objects.using(alias).filter(pk=row.pk).update(
                previous_stock_value=previous_value,
                previous_valuation_rate=previous_rate,
                value_difference=sle.stock_value_difference,
            )
            total += sle.stock_value_difference
        Reconciliation.objects.using(alias).filter(pk=document.pk).update(
            total_value_difference=total
        )


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_stockreconciliation_stockreconciliationitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockreconciliation',
            name='total_value_difference',
            field=models.DecimalField(decimal_places=9, default=Decimal('0'), editable=False, max_digits=30),
        ),
        migrations.AddField(
            model_name='stockreconciliationitem',
            name='previous_stock_value',
            field=models.DecimalField(blank=True, decimal_places=9, editable=False, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='stockreconciliationitem',
            name='previous_valuation_rate',
            field=models.DecimalField(blank=True, decimal_places=9, editable=False, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='stockreconciliationitem',
            name='revalue_existing_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stockreconciliationitem',
            name='value_difference',
            field=models.DecimalField(blank=True, decimal_places=9, editable=False, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='stockreconciliationitem',
            name='receipt_rate',
            field=models.DecimalField(decimal_places=9, default=Decimal('0'), max_digits=30, verbose_name='Receipt or target valuation rate'),
        ),
        migrations.RunPython(backfill_reconciliation_values, migrations.RunPython.noop),
    ]
