# Generated by Django 5.2.17 on 2026-09-30 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_stockledgerentry_is_value_reset'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockreconciliation',
            name='native_gl',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
