# Generated by Django 5.2.17 on 2026-09-30 10:06

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_itemprice_legacy_customer_name_and_more'),
        ('stock', '0011_stockreconciliation_native_gl'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemReorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=1)),
                ('warehouse_reorder_level', models.DecimalField(decimal_places=9, default=Decimal('0'), max_digits=30)),
                ('warehouse_reorder_qty', models.DecimalField(decimal_places=9, default=Decimal('0'), max_digits=30)),
                ('material_request_type', models.CharField(choices=[('Purchase', 'Purchase'), ('Transfer', 'Transfer'), ('Material Issue', 'Material Issue'), ('Manufacture', 'Manufacture')], default='Purchase', max_length=20)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reorder_levels', to='catalog.item')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_reorder_levels', to='stock.warehouse')),
                ('warehouse_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item_reorder_groups', to='stock.warehouse')),
            ],
            options={
                'db_table': 'item_reorder',
                'ordering': ('item', 'position'),
                'constraints': [models.UniqueConstraint(fields=('item', 'position'), name='unique_item_reorder_position'), models.UniqueConstraint(fields=('item', 'warehouse'), name='unique_item_reorder_warehouse')],
            },
        ),
    ]
