# Generated by Django 5.2.17 on 2026-09-30 14:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='نام مشتری')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='کد')),
                ('contact', models.CharField(blank=True, max_length=100, verbose_name='نام تماس')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='تلفن')),
                ('city', models.CharField(blank=True, max_length=80, verbose_name='شهر')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=40, unique=True, verbose_name='کد کالا')),
                ('name', models.CharField(max_length=160, verbose_name='نام کالا')),
                ('category', models.CharField(max_length=80, verbose_name='دسته\u200cبندی')),
                ('unit', models.CharField(default='عدد', max_length=30, verbose_name='واحد')),
                ('sale_price', models.DecimalField(decimal_places=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت فروش')),
                ('purchase_price', models.DecimalField(decimal_places=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت خرید')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='موجودی')),
                ('reorder_level', models.PositiveIntegerField(default=10, verbose_name='حد سفارش')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='نام تامین\u200cکننده')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='کد')),
                ('contact', models.CharField(blank=True, max_length=100, verbose_name='نام تماس')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='تلفن')),
                ('city', models.CharField(blank=True, max_length=80, verbose_name='شهر')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('sales', 'فروش'), ('purchase', 'خرید')], max_length=8, verbose_name='نوع')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('confirmed', 'تایید شده')], default='draft', max_length=10, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تایید')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='demo.customer')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='demo.supplier')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='تعداد')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت واحد')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='demo.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='demo.order')),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change', models.IntegerField(verbose_name='تغییر موجودی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='demo.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='demo.order')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
