# Generated by Django 5.2.17 on 2026-09-30 15:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def backfill_fulfillments(apps, schema_editor):
    Order = apps.get_model('demo', 'Order')
    Fulfillment = apps.get_model('demo', 'Fulfillment')
    StockMovement = apps.get_model('demo', 'StockMovement')
    for order in Order.objects.filter(status='confirmed').iterator():
        if StockMovement.objects.filter(order_id=order.pk).exists():
            Fulfillment.objects.create(order_id=order.pk,
                                       completed_at=order.confirmed_at or order.created_at)


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_customer_is_active_item_is_active_supplier_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ لغو'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('confirmed', 'تایید شده'), ('cancelled', 'لغو شده')], default='draft', max_length=10, verbose_name='وضعیت'),
        ),
        migrations.CreateModel(
            name='Fulfillment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان تحویل یا دریافت')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='fulfillment', to='demo.order')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=16, validators=[django.core.validators.MinValueValidator(1)], verbose_name='مبلغ')),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان صدور')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='demo.order')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=16, validators=[django.core.validators.MinValueValidator(1)], verbose_name='مبلغ')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='شماره پیگیری')),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان پرداخت')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='demo.invoice')),
            ],
            options={
                'ordering': ['paid_at', 'pk'],
            },
        ),
        migrations.RunPython(backfill_fulfillments, migrations.RunPython.noop),
    ]
