# Generated by Django 5.2.17 on 2026-09-30 16:28

from datetime import timedelta

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def backfill_ledger(apps, schema_editor):
    Item = apps.get_model('demo', 'Item')
    Order = apps.get_model('demo', 'Order')
    StockMovement = apps.get_model('demo', 'StockMovement')
    order_kinds = dict(Order.objects.values_list('pk', 'kind'))
    for item in Item.objects.all().iterator():
        movements = list(StockMovement.objects.filter(item_id=item.pk).order_by('created_at', 'pk'))
        opening = item.stock - sum(movement.change for movement in movements)
        if opening:
            first_time = movements[0].created_at if movements else django.utils.timezone.now()
            StockMovement.objects.create(
                item_id=item.pk, source='opening', order_id=None, change=opening,
                balance_before=0, balance_after=opening,
                note='موجودی افتتاحیه',
                created_at=first_time - timedelta(seconds=1),
            )
        balance = opening
        for movement in movements:
            movement.balance_before = balance
            balance += movement.change
            movement.balance_after = balance
            movement.source = order_kinds.get(movement.order_id, 'adjustment')
            movement.save(update_fields=['balance_before', 'balance_after', 'source'])


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_order_cancelled_at_alter_order_status_fulfillment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='balance_after',
            field=models.IntegerField(default=0, verbose_name='ماندهٔ بعد'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='balance_before',
            field=models.IntegerField(default=0, verbose_name='ماندهٔ قبل'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='note',
            field=models.CharField(blank=True, max_length=255, verbose_name='دلیل یا توضیح'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='source',
            field=models.CharField(choices=[('opening', 'موجودی افتتاحیه'), ('sales', 'تحویل فروش'), ('purchase', 'دریافت خرید'), ('adjustment', 'اصلاح موجودی')], default='adjustment', max_length=12, verbose_name='نوع گردش'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='demo.order'),
        ),
        migrations.RunPython(backfill_ledger, migrations.RunPython.noop),
    ]
