# Generated by Django 5.2.17 on 2026-09-30 20:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def assign_payment_keys(apps, schema_editor):
    Payment = apps.get_model('demo', 'Payment')
    for pk in Payment.objects.using(schema_editor.connection.alias).values_list('pk', flat=True):
        Payment.objects.using(schema_editor.connection.alias).filter(pk=pk).update(
            idempotency_key=uuid.uuid4())


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_stockmovement_balance_after_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='idempotency_key',
            field=models.UUIDField(null=True, editable=False, verbose_name='شناسهٔ درخواست'),
        ),
        migrations.RunPython(assign_payment_keys, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='payment', name='idempotency_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسهٔ درخواست'),
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50, verbose_name='رویداد')),
                ('object_type', models.CharField(max_length=50, verbose_name='نوع سند')),
                ('object_id', models.CharField(max_length=50, verbose_name='شناسهٔ سند')),
                ('object_label', models.CharField(max_length=160, verbose_name='عنوان سند')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='جزئیات')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='زمان')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erp_audit_events', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
