# Generated by Django 5.2.17 on 2026-09-30 21:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_payment_idempotency_key_auditevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_date', models.DateField(blank=True, null=True, verbose_name='تاریخ جلسه')),
                ('attendees', models.TextField(blank=True, verbose_name='حاضران')),
                ('outcome', models.CharField(choices=[('pending', 'در انتظار تصمیم'), ('stop', 'توقف'), ('discovery', 'فاز کشف'), ('pilot', 'پایلوت محدود')], default='pending', max_length=20, verbose_name='نتیجه')),
                ('architecture', models.CharField(choices=[('undecided', 'هنوز تعیین نشده'), ('erpnext_standard', 'ERPNext استاندارد'), ('erpnext_custom', 'ERPNext با Custom App محدود'), ('erpnext_api_ui', 'ERPNext با رابط اختصاصی از API'), ('independent', 'محصول مستقل')], default='undecided', max_length=30, verbose_name='گزینهٔ معماری')),
                ('positives', models.TextField(blank=True, verbose_name='نکات مثبت')),
                ('concerns', models.TextField(blank=True, verbose_name='نگرانی\u200cها و شکاف\u200cها')),
                ('gap_summary', models.TextField(blank=True, verbose_name='جمع\u200cبندی نیاز و فاصلهٔ واقعی')),
                ('next_step', models.TextField(blank=True, verbose_name='اقدام بعدی')),
                ('owner', models.CharField(blank=True, max_length=160, verbose_name='مالک اقدام')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='موعد پیگیری')),
                ('budget_ceiling', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='سقف بودجه (تومان)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_erp_decisions', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_erp_decisions', to=settings.AUTH_USER_MODEL, verbose_name='آخرین ویرایش\u200cکننده')),
            ],
            options={
                'ordering': ['-meeting_date', '-created_at'],
            },
        ),
    ]
