# Generated by Django 5.2.17 on 2026-09-30 21:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0006_managementdecision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FitGapItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('accounting', 'حسابداری و مالی'), ('tax', 'مالیات و الزامات قانونی'), ('sales', 'فروش و قیمت\u200cگذاری'), ('purchase', 'خرید و تامین'), ('inventory', 'انبار و لجستیک'), ('hr', 'منابع انسانی'), ('multi_company', 'چندشرکتی و شعب'), ('manufacturing', 'تولید'), ('integration', 'اتصال\u200cها و تبادل داده'), ('reporting', 'گزارش و تحلیل'), ('security', 'امنیت و دسترسی'), ('data', 'داده و مهاجرت'), ('other', 'سایر')], max_length=30, verbose_name='حوزه')),
                ('title', models.CharField(max_length=180, verbose_name='عنوان نیاز')),
                ('requirement', models.TextField(verbose_name='نیاز واقعی کسب\u200cوکار')),
                ('current_process', models.TextField(blank=True, verbose_name='فرایند یا ابزار فعلی')),
                ('evidence', models.TextField(blank=True, verbose_name='منبع و شاهد نیاز')),
                ('fit', models.CharField(choices=[('unknown', 'نیازمند بررسی'), ('standard', 'پوشش استاندارد ERPNext'), ('configuration', 'قابل حل با پیکربندی'), ('custom', 'نیازمند Custom App'), ('integration', 'نیازمند اتصال'), ('gap', 'شکاف تاییدشده')], default='unknown', max_length=20, verbose_name='وضعیت انطباق')),
                ('solution', models.TextField(blank=True, verbose_name='راهکار پیشنهادی')),
                ('acceptance_criteria', models.TextField(blank=True, verbose_name='معیار پذیرش')),
                ('priority', models.CharField(choices=[('critical', 'حیاتی'), ('high', 'بالا'), ('medium', 'متوسط'), ('low', 'پایین')], default='medium', max_length=10, verbose_name='اولویت')),
                ('effort', models.CharField(choices=[('unknown', 'نیازمند برآورد'), ('xs', 'کمتر از ۳ نفر-روز'), ('s', '۳ تا ۱۰ نفر-روز'), ('m', '۲ تا ۴ هفته'), ('l', '۱ تا ۲ ماه'), ('xl', 'بیش از ۲ ماه')], default='unknown', max_length=10, verbose_name='برآورد تلاش')),
                ('risk', models.CharField(choices=[('low', 'کم'), ('medium', 'متوسط'), ('high', 'بالا')], default='medium', max_length=10, verbose_name='ریسک')),
                ('phase', models.CharField(choices=[('discovery', 'فاز کشف'), ('pilot', 'پایلوت'), ('later', 'پس از پایلوت'), ('out', 'خارج از محدوده')], default='discovery', max_length=12, verbose_name='فاز هدف')),
                ('cost_low', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='حداقل هزینه (تومان)')),
                ('cost_high', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='حداکثر هزینه (تومان)')),
                ('owner', models.CharField(blank=True, max_length=160, verbose_name='مالک بررسی یا اجرا')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('validated', 'اعتبارسنجی\u200cشده'), ('approved', 'مصوب'), ('deferred', 'موکول\u200cشده')], default='draft', max_length=12, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fit_gap_items', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fit_gap_items', to='demo.managementdecision', verbose_name='تصمیم جلسه')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_fit_gap_items', to=settings.AUTH_USER_MODEL, verbose_name='آخرین ویرایش\u200cکننده')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
