# Generated by Django 5.2.17 on 2026-09-30 21:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0007_fitgapitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillOfMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد BOM')),
                ('version', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='نسخه')),
                ('output_quantity', models.DecimalField(decimal_places=3, default=1, max_digits=12, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='مقدار خروجی')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('active', 'فعال'), ('obsolete', 'منسوخ')], default='draft', max_length=10, verbose_name='وضعیت')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات مهندسی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boms', to='demo.item', verbose_name='محصول')),
            ],
            options={
                'ordering': ['product__name', '-version'],
            },
        ),
        migrations.CreateModel(
            name='BOMComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='مقدار مصرف')),
                ('scrap_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درصد ضایعات')),
                ('sequence', models.PositiveIntegerField(default=10, verbose_name='ترتیب')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='توضیح')),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='demo.billofmaterials', verbose_name='BOM')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_boms', to='demo.item', verbose_name='جزء')),
            ],
            options={
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='billofmaterials',
            constraint=models.UniqueConstraint(fields=('product', 'version'), name='demo_bom_product_version'),
        ),
        migrations.AddConstraint(
            model_name='billofmaterials',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('product',), name='demo_one_active_bom_per_product'),
        ),
        migrations.AddConstraint(
            model_name='bomcomponent',
            constraint=models.UniqueConstraint(fields=('bom', 'item'), name='demo_unique_bom_component'),
        ),
    ]
