# Generated by Django 5.2.17 on 2026-09-30 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0008_billofmaterials_bomcomponent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='billofmaterials',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان فعال\u200cسازی'),
        ),
        migrations.AddField(
            model_name='billofmaterials',
            name='activated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_boms', to=settings.AUTH_USER_MODEL, verbose_name='فعال\u200cکننده'),
        ),
        migrations.AddField(
            model_name='billofmaterials',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_boms', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده'),
        ),
        migrations.AddField(
            model_name='billofmaterials',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_boms', to=settings.AUTH_USER_MODEL, verbose_name='آخرین ویرایش\u200cکننده'),
        ),
    ]
