# Generated by Django 5.2.17 on 2026-10-01 02:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0009_billofmaterials_activated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='کد حساب')),
                ('name', models.CharField(max_length=120, verbose_name='نام حساب')),
                ('account_type', models.CharField(choices=[('asset', 'دارایی'), ('liability', 'بدهی'), ('equity', 'حقوق مالکانه'), ('income', 'درآمد'), ('expense', 'هزینه')], max_length=12, verbose_name='نوع حساب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(max_length=30, verbose_name='نوع سند مبنا')),
                ('source_id', models.PositiveBigIntegerField(verbose_name='شناسهٔ سند مبنا')),
                ('source_label', models.CharField(max_length=80, verbose_name='شمارهٔ سند مبنا')),
                ('description', models.CharField(max_length=255, verbose_name='شرح')),
                ('posted_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='زمان ثبت')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_journal_entries', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
            ],
            options={
                'ordering': ['-posted_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=0, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='بدهکار')),
                ('credit', models.DecimalField(decimal_places=0, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='بستانکار')),
                ('memo', models.CharField(blank=True, max_length=180, verbose_name='شرح ردیف')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='demo.account', verbose_name='حساب')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='demo.journalentry', verbose_name='سند حسابداری')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(fields=('source_type', 'source_id'), name='demo_unique_accounting_source'),
        ),
        migrations.AddConstraint(
            model_name='journalline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('credit', 0), ('debit__gt', 0)), models.Q(('credit__gt', 0), ('debit', 0)), _connector='OR'), name='demo_journal_line_one_side'),
        ),
    ]
