# Generated by Django 5.2.17 on 2026-10-01 02:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0010_account_journalentry_journalline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='source',
            field=models.CharField(choices=[('opening', 'موجودی افتتاحیه'), ('sales', 'تحویل فروش'), ('purchase', 'دریافت خرید'), ('adjustment', 'اصلاح موجودی'), ('manufacture_issue', 'مصرف در تولید'), ('manufacture_receipt', 'رسید محصول تولیدی')], default='adjustment', max_length=24, verbose_name='نوع گردش'),
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='تعداد برنامه\u200cریزی\u200cشده')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('released', 'آزادشده برای تولید'), ('completed', 'تکمیل\u200cشده'), ('cancelled', 'لغوشده')], default='draft', max_length=12, verbose_name='وضعیت')),
                ('planned_start', models.DateField(default=django.utils.timezone.localdate, verbose_name='شروع برنامه\u200cریزی\u200cشده')),
                ('due_date', models.DateField(verbose_name='موعد تکمیل')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت تولید')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('released_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان آزادسازی')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تکمیل')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان لغو')),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='demo.billofmaterials', verbose_name='نسخهٔ BOM')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_work_orders', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_work_orders', to=settings.AUTH_USER_MODEL)),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_work_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='demo.workorder'),
        ),
        migrations.CreateModel(
            name='WorkOrderMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='مقدار مورد نیاز')),
                ('unit_cost', models.DecimalField(decimal_places=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='بهای واحد مبنا')),
                ('sequence', models.PositiveIntegerField(default=10, verbose_name='ترتیب')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_order_materials', to='demo.item')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='demo.workorder')),
            ],
            options={
                'ordering': ['sequence', 'id'],
                'constraints': [models.UniqueConstraint(fields=('work_order', 'item'), name='demo_unique_work_order_material')],
            },
        ),
    ]
