# Generated by Django 5.2.17 on 2026-10-01 02:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0011_alter_stockmovement_source_workorder_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demand_quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='تقاضای برنامه')),
                ('due_date', models.DateField(verbose_name='تاریخ نیاز')),
                ('status', models.CharField(choices=[('open', 'باز'), ('closed', 'بسته\u200cشده')], default='open', max_length=10, verbose_name='وضعیت')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت برنامه\u200cریزی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان اجرا')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان بستن')),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_plans', to='demo.billofmaterials')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_production_plans', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_production_plans', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_plans', to='demo.item')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='source_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='demo.productionplan'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='source_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='demo.productionplan'),
        ),
        migrations.CreateModel(
            name='ProductionPlanLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(verbose_name='سطح')),
                ('sequence', models.PositiveIntegerField(verbose_name='ترتیب')),
                ('gross_requirement', models.PositiveIntegerField(verbose_name='نیاز ناخالص')),
                ('allocated_stock', models.PositiveIntegerField(default=0, verbose_name='تامین از موجودی')),
                ('scheduled_receipts', models.PositiveIntegerField(default=0, verbose_name='دریافت برنامه\u200cریزی\u200cشده')),
                ('net_requirement', models.PositiveIntegerField(default=0, verbose_name='نیاز خالص')),
                ('supply_type', models.CharField(choices=[('make', 'ساخت'), ('buy', 'خرید'), ('covered', 'تامین\u200cشده')], max_length=10, verbose_name='پیشنهاد تامین')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_plan_lines', to='demo.item')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='demo.productionplanline')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='demo.productionplan')),
                ('supply_bom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_plan_lines', to='demo.billofmaterials')),
            ],
            options={
                'ordering': ['sequence', 'id'],
            },
        ),
    ]
