# Generated by Django 5.2.17 on 2026-10-01 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0012_productionplan_order_source_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='source_plan_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='demo.productionplanline'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='source_plan_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='demo.productionplanline'),
        ),
    ]
