# Generated by Django 5.2.17 on 2026-10-03 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0013_order_source_plan_line_workorder_source_plan_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionplan',
            name='source_order_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_plans', to='demo.orderline', verbose_name='قلم سفارش مشتری'),
        ),
    ]
