# Generated by Django 5.2.17 on 2026-10-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0014_productionplan_source_order_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='سررسید'),
        ),
        migrations.AddField(
            model_name='order',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='موعد تحویل / دریافت'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_due_date',
            field=models.DateField(blank=True, null=True, verbose_name='سررسید صورتحساب'),
        ),
    ]
