# Generated by Django 5.2.17 on 2026-10-03 15:28

import demo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0015_invoice_due_date_order_due_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanningPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_weekdays', models.JSONField(default=demo.models.default_workdays, verbose_name='روزهای کاری هفته')),
                ('holidays', models.JSONField(blank=True, default=list, verbose_name='تعطیلات (تاریخ میلادی)')),
            ],
        ),
        migrations.AddField(
            model_name='billofmaterials',
            name='manufacturing_days',
            field=models.PositiveIntegerField(default=1, verbose_name='مدت ساخت (روز کاری)'),
        ),
        migrations.AddField(
            model_name='item',
            name='lead_time_days',
            field=models.PositiveIntegerField(default=0, verbose_name='زمان تامین (روز کاری)'),
        ),
        migrations.AddField(
            model_name='productionplan',
            name='schedule_snapshot',
            field=models.JSONField(blank=True, default=dict, verbose_name='مبنای زمان\u200cبندی'),
        ),
        migrations.AddField(
            model_name='productionplanline',
            name='release_date',
            field=models.DateField(blank=True, null=True, verbose_name='زمان شروع / سفارش\u200cگذاری'),
        ),
        migrations.AddField(
            model_name='productionplanline',
            name='required_date',
            field=models.DateField(blank=True, null=True, verbose_name='موعد نیاز'),
        ),
    ]
