# Generated by Django 5.2.17 on 2026-10-03 15:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0016_planningpolicy_billofmaterials_manufacturing_days_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=160, verbose_name='عنوان سناریو')),
                ('parameters', models.JSONField(default=dict, verbose_name='فرض\u200cهای تغییر')),
                ('baseline', models.JSONField(default=dict, verbose_name='مبنای مقایسه')),
                ('result', models.JSONField(default=dict, verbose_name='نتیجهٔ شبیه\u200cسازی')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('applied_plan', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applied_scenario', to='demo.productionplan')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scenarios', to='demo.productionplan')),
            ],
        ),
    ]
