# Generated by Django 5.2.17 on 2026-10-03 15:53

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0017_planscenario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='billofmaterials',
            name='labor_cost_per_unit',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='دستمزد هر واحد محصول (تومان)'),
        ),
        migrations.AddField(
            model_name='billofmaterials',
            name='overhead_cost_per_unit',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='سربار هر واحد محصول (تومان)'),
        ),
        migrations.CreateModel(
            name='OrderCostEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot', models.JSONField(default=dict, verbose_name='برآورد تثبیت\u200cشده')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_estimates', to='demo.order')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
