# Generated by Django 5.2.17 on 2026-10-03 16:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0018_billofmaterials_labor_cost_per_unit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_limit', models.DecimalField(decimal_places=0, default=100000000, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='سقف خرید بدون تایید مدیر (تومان)')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='approval_basis',
            field=models.JSONField(blank=True, default=dict, verbose_name='مبنای تایید'),
        ),
        migrations.AddField(
            model_name='order',
            name='approval_decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='approval_decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_approval_decisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='approval_decision_reason',
            field=models.TextField(blank=True, verbose_name='دلیل تصمیم'),
        ),
        migrations.AddField(
            model_name='order',
            name='approval_reason',
            field=models.TextField(blank=True, verbose_name='دلیل درخواست'),
        ),
        migrations.AddField(
            model_name='order',
            name='approval_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='approval_status',
            field=models.CharField(choices=[('not_requested', 'ارسال نشده'), ('pending', 'منتظر مدیر'), ('approved', 'تایید مدیر'), ('rejected', 'رد شده')], default='not_requested', max_length=15, verbose_name='تایید خرید'),
        ),
    ]
