# Generated by Django 5.2.17 on 2026-10-03 16:30

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0019_purchasepolicy_order_approval_basis_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FulfillmentBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('request_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('legacy', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fulfillment_batches', to='demo.order')),
            ],
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='fulfillment_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='demo.fulfillmentbatch'),
        ),
        migrations.CreateModel(
            name='FulfillmentBatchLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=14)),
                ('unit_cost', models.DecimalField(decimal_places=0, max_digits=14)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='demo.fulfillmentbatch')),
                ('order_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batch_lines', to='demo.orderline')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_charge', to='demo.fulfillmentbatch')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='demo.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_quantity', models.PositiveIntegerField(default=0)),
                ('rejected_quantity', models.PositiveIntegerField(default=0)),
                ('quality_reason', models.TextField(verbose_name='نتیجه و دلیل کنترل کیفیت')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('request_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('legacy', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_batches', to='demo.workorder')),
            ],
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='production_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='demo.productionbatch'),
        ),
        migrations.CreateModel(
            name='ProductionBatchMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=0, max_digits=14)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='demo.productionbatch')),
                ('work_order_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batch_materials', to='demo.workordermaterial')),
            ],
        ),
    ]
