# Generated by Django 5.2.17 on 2026-10-03 18:01

import django.core.validators
from decimal import Decimal, InvalidOperation
from django.db import migrations, models


def validate_existing_amounts(apps, schema_editor):
    """Refuse unsafe legacy values before changing any column's storage type."""
    connection = schema_editor.connection
    quote = connection.ops.quote_name
    targets = [('demo_managementdecision', ['budget_ceiling']),
               ('demo_fitgapitem', ['cost_low', 'cost_high'])]
    with connection.cursor() as cursor:
        for table, fields in targets:
            columns = ', '.join(quote(name) for name in ['id', *fields])
            cursor.execute(f'SELECT {columns} FROM {quote(table)}')
            while rows := cursor.fetchmany(1000):
                for row in rows:
                    for field, value in zip(fields, row[1:]):
                        if value is None:
                            continue
                        try:
                            number = Decimal(str(value))
                            safe = (number.is_finite() and number == number.to_integral_value()
                                    and 0 <= number <= 999999999999999999
                                    and not (connection.vendor == 'sqlite' and isinstance(value, float)))
                        except (InvalidOperation, ValueError):
                            safe = False
                        if not safe:
                            raise RuntimeError(f'Unsafe existing amount in {table}.{field}, row {row[0]}; '
                                               'review the source data before retrying. No amounts were rounded.')


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0021_preserve_completed_operations'),
    ]

    operations = [
        migrations.RunPython(validate_existing_amounts, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='fitgapitem',
            name='cost_high',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999999999999999)], verbose_name='حداکثر هزینه (تومان)'),
        ),
        migrations.AlterField(
            model_name='fitgapitem',
            name='cost_low',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999999999999999)], verbose_name='حداقل هزینه (تومان)'),
        ),
        migrations.AlterField(
            model_name='managementdecision',
            name='budget_ceiling',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999999999999999)], verbose_name='سقف بودجه (تومان)'),
        ),
    ]
